name: deploy

on:
  push:
    branches:
    - main

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Build Content
      run: |
        jupyter-book build source
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: source/_build/html
